AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  job-sentinel

  Sample SAM Template for job-sentinel
  
Globals:
  Function:
    Timeout: 30

Resources:
  CheckJobInactivityFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: project/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          SEQUENCER_ADDRESS: "0x238b4E35dAed6100C6162fAE4510261f88996EC9"
          RPC_PROVIDER: "https://rpc.ankr.com/eth"
          DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1271111101227991060/IXZasRFdYP1cmg4KFM74AMtjdZuTa54zr0TRbzDUnbwhS_ATyXmcK-BGamo63EdMNYJN"
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(15 seconds)
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - app.ts

Outputs:
  CheckJobInactivityFunctionArn:
    Description: "Check Job Inactivity Lambda Function ARN"
    Value: !GetAtt CheckJobInactivityFunction.Arn
