import { InterfaceAbi } from "ethers";

export const jobAbi : InterfaceAbi= [
  {"inputs":[{"internalType":"address","name":"_sequencer","type":"address"},{"internalType":"address","name":"_litePsm","type":"address"},{"internalType":"uint256","name":"_rushThreshold","type":"uint256"},{"internalType":"uint256","name":"_cutThreshold","type":"uint256"},{"internalType":"uint256","name":"_gushThreshold","type":"uint256"}],"stateMutability":"nonpayable","type":"constructor"},
  {"inputs":[{"internalType":"bytes32","name":"network","type":"bytes32"}],"name":"NotMaster","type":"error"},
  {"inputs":[{"internalType":"bytes4","name":"fn","type":"bytes4"}],"name":"ThresholdNotReached","type":"error"},
  {"inputs":[{"internalType":"bytes4","name":"fn","type":"bytes4"}],"name":"UnsupportedFunction","type":"error"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"network","type":"bytes32"},{"indexed":true,"internalType":"bytes4","name":"action","type":"bytes4"}],"name":"Work","type":"event"},
  {"inputs":[],"name":"cutThreshold","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"gushThreshold","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"litePsm","outputs":[{"internalType":"contract LitePsmLike","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"rushThreshold","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"sequencer","outputs":[{"internalType":"contract SequencerLike","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bytes32","name":"network","type":"bytes32"},{"internalType":"bytes","name":"args","type":"bytes"}],"name":"work","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"bytes32","name":"network","type":"bytes32"}],"name":"workable","outputs":[{"internalType":"bool","name":"","type":"bool"},{"internalType":"bytes","name":"","type":"bytes"}],"stateMutability":"view","type":"function"}]